### ISSUE TITLE
Can't compile marlin with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER defined

### ISSUE THREAD

**Issue by monkeydave** [ErikZalm/Marlin#1205]
Using the latest marlin I am unable to compile without errors with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER defined, board type makes no difference. This also affects MaKrPanel as it uses also uses DOGLCD

The error is "dogm_lcd_implementation.h:361:149: error: invalid conversion from ‘const char*’ to ‘char*’" 
Full compile error list here https://gist.github.com/monkeydave/77d714fd84f190c0174a

I think I have traced the error to commit e69313fc2bed33f6b436af2902cbb155a6928050

This commit merged these two functions
    lcd_implementation_drawmenu_setting_edit_generic()
    lcd_implementation_drawmenu_setting_edit_generic_P()
into one called
    _drawmenu_setting_edit_generic(uint8_t row, const char* pstr, char pre_char, char* data, bool pgm)

If I change the definition for _drawmenu_setting_edit_generic to _drawmenu_setting_edit_generic(uint8_t row, const char* pstr, char pre_char,  const char* data, bool pgm) I can compile without error. I don't know the LCD code well so I don't know what the ramifications of this change could be, so I would rather not submit a pull request.

@thinkyhead as it was your commit

**Comment by monkeydave** [comment]
2ec2bf1564b9fcb451d5be043b751f8966954c3 should have solved this

**Comment by leobelen** [comment]
in fact, right now with Arduino 1.5.8, stack configuration and only REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER defined, now it fails with:

ultralcd.cpp: In function 'void lcd_control_volumetric_menu()':
ultralcd.cpp:133:103: error: 'lcd_implementation_drawmenu_setting_edit_callback_float43_selected' was not declared in this scope
                 lcd_implementation_drawmenu_ ## type ## _selected (_drawLineNr, _label_pstr , ## args ); \
                                                                                                       ^
ultralcd.cpp:148:55: note: in expansion of macro 'MENU_ITEM'
 #define MENU_ITEM_EDIT_CALLBACK(type, label, args...) MENU_ITEM(setting_edit_callback_ ## type, label, PSTR(label) , ## args )
                                                       ^
ultralcd.cpp:886:3: note: in expansion of macro 'MENU_ITEM_EDIT_CALLBACK'
   MENU_ITEM_EDIT_CALLBACK(float43, MSG_FILAMENT_SIZE_EXTRUDER_0, &filament_size[0], DEFAULT_NOMINAL_FILAMENT_DIA - .5, DEFAULT_NOMINAL_FILAMENT_DIA + .5, calculate_volumetric_multipliers);
   ^
ultralcd.cpp:135:90: error: 'lcd_implementation_drawmenu_setting_edit_callback_float43' was not declared in this scope
                 lcd_implementation_drawmenu_ ## type (_drawLineNr, _label_pstr , ## args ); \
                                                                                          ^
ultralcd.cpp:148:55: note: in expansion of macro 'MENU_ITEM'
 #define MENU_ITEM_EDIT_CALLBACK(type, label, args...) MENU_ITEM(setting_edit_callback_ ## type, label, PSTR(label) , ## args )
                                                       ^
ultralcd.cpp:886:3: note: in expansion of macro 'MENU_ITEM_EDIT_CALLBACK'
   MENU_ITEM_EDIT_CALLBACK(float43, MSG_FILAMENT_SIZE_EXTRUDER_0, &filament_size[0], DEFAULT_NOMINAL_FILAMENT_DIA - .5, DEFAULT_NOMINAL_FILAMENT_DIA + .5, calculate_volumetric_multipliers);
   ^

**Comment by leobelen** [comment]
Now, in the same situation, but Arduino 1.0.6, it fails with:

ultralcd.cpp: In function 'void lcd_control_volumetric_menu()':
ultralcd.cpp:886: error: 'lcd_implementation_drawmenu_setting_edit_callback_float43_selected' was not declared in this scope
ultralcd.cpp:886: error: 'lcd_implementation_drawmenu_setting_edit_callback_float43' was not declared in this scope

**Comment by monkeydave** [comment]
@leobelen see issue #1301

**Comment by leobelen** [comment]
Thanks @monkeydave. Also, update f8aa5ff solves it completely. Now it compiles with no problem in both versions of Arduino on Mac.
