### ISSUE TITLE
Can't compile for Melzi

### ISSUE THREAD

**Issue by Lukelectro** [ErikZalm/Marlin#1243]
Sory to make a new issue instead of fixing one, but I get:

Marlin_main.cpp:360: error: ‘analogInputToDigitalPin’ was not declared in this scope
Marlin_main.cpp:360: error: ‘analogInputToDigitalPin’ was not declared in this scope
Marlin_main.cpp:360: error: ‘analogInputToDigitalPin’ was not declared in this scope
Marlin_main.cpp:360: error: ‘analogInputToDigitalPin’ was not declared in this scope

When I try to compile the current devellopment branch for Melzi
(Add 

#define MOTHERBOARD BOARD_MELZI 

above 

#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_ULTIMAKER
#endif 
)

The analogInputToDigitalPin is part of the Sensitive_pins declaration in pins.h, its in there 4 times hence 4 errors.

When compiling for the ultiboard it compiles fine so I guess it is somewhere in the part of pins.h applicable to melzi.

I´ll keep looking into this.

**Comment by alhirzel** [comment]
@Lukelectro could you test #1291 ?

**Comment by Lukelectro** [comment]
I would like to, but I'm still new to github. So, here is what I think I should do, please CMIIW:

1) Get your modified code
2) See if "it works" on my melzi (in this case only see if it compiles)
3) report results here.

Step 1 is the problem. If I just copy-paste https://github.com/alhirzel/Marlin/blob/Development/Marlin/Marlin.h to replace my own, I get all sorts of unrelated errors because I just replaced a single file and all sorts of references go wrong. (I should instead clone the entire project, then pull all files you changed, I think)

However, if I just add

#ifndef analogInputToDigitalPin
# define analogInputToDigitalPin(p) ((p) + A0)
#endif

to the "old" marlin.h (the one I had), and remove my own workaround, it compiles fine.

**Comment by boelle** [comment]
you can see what changes was made here if it helps you

https://github.com/ErikZalm/Marlin/pull/1291/files

**Comment by Lukelectro** [comment]
Thats where I got the file from. But I think it would help me more if I read https://help.github.com/categories/bootcamp/ . ;)

**Comment by gregrebholz** [comment]
@Lukelectro Try this... from a git client installed on your machine:
1. git clone https://github.com/ErikZalm/Marlin (this gets you a whole clone of the Marlin git repository)
2. git checkout Development (this puts your working directory on the latest bleeding edge)
3. git fetch origin pull/1291/head:testing (this is creating a new local branch of your git repo called "testing" and populating it with the changes in pull request 1291 from your repo's origin - ErikZalm/Marlin)
4. git checkout testing (to move this new branch)

Then the code in your directory should be exactly as it would be if pull req 1291 is merged into the Development branch.

**Comment by Lukelectro** [comment]
Thanks for your help. The code in my directory is indeed the same (it has the 

#ifndef analogInputToDigitalPin
#define analogInputToDigitalPin(p) ((p) + A0)
#endif 

bit added)

And, as expected, it compiles.

I have not changed all the settings to suit my printer yet, so I have not done other tests. Yet.

**Comment by alhirzel** [comment]
Glad this fixed the issue for you. =]

**Comment by Lukelectro** [comment]
Yes. Closing.
