### ISSUE TITLE
Menu selection and Edit numbers encoder direction reversed 

### ISSUE THREAD

**Issue by GabeHC** [ErikZalm/Marlin#1275]
How do I change Menu selection and Numbers editing orientation to match the  LCD physical  layout.
means when turning dial clockwise menu selection goes up, and when editing numbers clockwise will increase numbers . currently it works opposite. 
  this issue can not be solved by swapping enc1 and enc2. cause it will swap them both. and when numbers works fine, menu selection gets reversed. 
  been tracing the code for few hours. don't have a clue how to do it. can you help?

**Comment by alhirzel** [comment]
I took a quick look, maybe you saw this already but I think it's done inside ultralcd.cpp:lcd_buttons_update() . That code could get re-worked to be "reversible". Is this the info you're looking for?

**Comment by boelle** [comment]
it must be what he was looking for since no answer yet... can always reopen if there is an issue with marlin

**Comment by GabeHC** [comment]
it's in ultralcd.cpp all right, But lcd_buttons_update is not the problem. it is in the menu marco section, Menu item start from the top and it is been absolute map to encoder position, means when encoder position increases menu selection go down, still don't know how to map it backward!
any idea?

**Comment by nophead** [comment]
Why do you want it to go backwards? Moving to the next menu item is
increasing in most people view I think.

**Comment by boelle** [comment]
+1 to what nophead said... going clockwise would move down to next item... 

maybe attach a GPS and do it backwards if below equator like in australia ?

**Comment by GabeHC** [comment]
Don't know how your LCD works, but my Reprap Discount Smart LCD work like this, 
![marlin_menu](https://cloud.githubusercontent.com/assets/5255323/5615189/cb42d5ae-9533-11e4-8332-20a5d4d6f5d9.jpg)
when turning dial clockwise menu cursor go downward, when turning CCK cursor go upward,
this is totally against my space conception!

**Comment by nophead** [comment]
I doubt anybody else sees it like that. You seem to be thinking there is a
mechanical relationship between the knob and the cursor rather than a
logical one.

**Comment by boelle** [comment]
i would call that as intended... counter clock is up.. pretty normal

2015-01-05 16:44 GMT+01:00 Gabriel Huang <notifications@github.com>:

**Comment by GabeHC** [comment]
Yes, I see it as a mechanical relationship, Knob place at the right side, when turning clockwise cursor should go up, this is how a gear works, and to the logical one, clock wise menu goes up is quite normal to me on this panel layout.

**Comment by GabeHC** [comment]
is there anyone can help thing  a way to change the program ?

**Comment by ve3sjk** [comment]
I am not on the new dev. branch but I can also confirm this issue. I have the full graphic controller

 

In the menu system CCW is down and CW is up on the cursor behavior

 

When changing values in other screens,

 

CCW increases the numbers and CW lowers them so to move higher from zero requires me to 

Turn the dial CCW…….

 

Which is backwards in my mind……

**Comment by GabeHC** [comment]
finally,
  do you have any idea to change it?

**Comment by ve3sjk** [comment]
I am not exactly where in the code I believe it’s in pins.h you need to find the

Section where the encoder pins are defined and reverse them. 

 

search for this in pins.h and interchange the BTN_EN1 and BTN_EN2 pin numbers. This may change based

On what board you have defined.

 

      #ifdef REPRAP_DISCOUNT_SMART_CONTROLLER

        #define BEEPER 37

 

        #define BTN_EN1 31 ---- reverse these

        #define BTN_EN2 33 ---- this is the default values

        #define BTN_ENC 35

**Comment by GabeHC** [comment]
That is not what I am looking for. I already swap EN1, EN2 Pins define. 

      #ifdef REPRAP_DISCOUNT_SMART_CONTROLLER
        #define BEEPER 37
        #define BTN_EN1 31
        #define BTN_EN2 33
         #ifdef BTN_ENC_REVERSE
          #define BTN_EN1 33   // Blue Screen Up Down reversed
          #define BTN_EN2 31
        #endif  
       #define BTN_ENC 35

it fix some encoder button which is connected reverse. 
Problem is when numbers work okay, Menu system goes backward.

in UltraLCD.cpp
when menu is printing start from menu item 1 from the very top. that is why when encoder increase menu cursor go down. since we don't know how many items in current menu at the time. still can't figure out a way to convert it to a reverse order.  

  /* Helper macros for menus */
#define START_MENU() do { \
    if (encoderPosition > 0x8000) encoderPosition = 0; \
    if (encoderPosition / ENCODER_STEPS_PER_MENU_ITEM < currentMenuViewOffset) currentMenuViewOffset = encoderPosition / ENCODER_STEPS_PER_MENU_ITEM;\
    uint8_t _lineNr = currentMenuViewOffset, _menuItemNr; \
    bool wasClicked = LCD_CLICKED;\
    for(uint8_t _drawLineNr = 0; _drawLineNr < LCD_HEIGHT; _drawLineNr++, _lineNr++) { \
        _menuItemNr = 0;
#define MENU_ITEM(type, label, args...) do { \
    if (_menuItemNr == _lineNr) { \
        if (lcdDrawUpdate) { \
            const char* _label_pstr = PSTR(label); \
            if ((encoderPosition / ENCODER_STEPS_PER_MENU_ITEM) == _menuItemNr) { \
                lcd_implementation_drawmenu_ ## type ## _selected (_drawLineNr, _label_pstr , ## args ); \
            }else{\
                lcd_implementation_drawmenu_ ## type (_drawLineNr, _label_pstr , ## args ); \
            }\
        }\
        if (wasClicked && (encoderPosition / ENCODER_STEPS_PER_MENU_ITEM) == _menuItemNr) {\
            lcd_quick_feedback(); \
            menu_action_ ## type ( args ); \
            return;\
        }\
    }\
    _menuItemNr++;\
} while(0)
