### ISSUE TITLE
Can't set LCD language to other than English

### ISSUE THREAD

**Issue by MatixYo** [ErikZalm/Marlin#1278]
After changing language to any other than English it stays on English. 
Probably LANGUAGE_CHOICE returns false.

**Comment by JoshyuNL** [comment]
Tested this on my Rambo board with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER, using a newly downloaded DEV zip.
 
And though I can't read most of the languages, they select and upload just fine on my setup.

With Russian though, the characters don't properly show. The main menu looks like this:
(https://cloud.githubusercontent.com/assets/7063136/5592050/17c7d3d0-91af-11e4-9cf1-5c784d5f4162.jpg)
Maybe it's down to my computer and it's installed languages (english W8.1) but it seems to show correct in the Arduino IDE.

The rest of them are working fine, for me at least.

**Comment by boelle** [comment]
closing as this seems fixed... reopen if russian does not work
