### ISSUE TITLE
When bed PID is enabled, compile fails.

### ISSUE THREAD

**Issue by andrewsil1** [ErikZalm/Marlin#1284]
#1249 introduced a constant called MAX_BED_PID which doesn't appear to be included anywhere, causing compilation to fail.

**Comment by JoshyuNL** [comment]
I can confirm that this fails to compile.

*temperature.cpp: In function 'void manage_heater()':
temperature.cpp:585: error: 'MAX_BED_PID' was not declared in this scope*

**Comment by MagoKimbra** [comment]
In temperature.cpp line 585 replace
if (pid_output > MAX_BED_PID)
width
if (pid_output > PID_MAX)

**Comment by andrewsil1** [comment]
If that's really the fix then the author should submit a pull request.  I'm not looking for a short term fix, the compile failure needs to be fixed in the code base.

Andy
Tiny keyboard, tiny messages.

On Jan 1, 2015, at 10:44 AM, MagoKimbra <notifications@github.com<mailto:notifications@github.com>> wrote:


In temperature.cpp line 585 replace
if (pid_output > MAX_BED_PID)
width
if (pid_output > PID_MAX)

-

**Comment by alhirzel** [comment]
resolved by #1286 ?

**Comment by andrewsil1** [comment]
Verified that this compilation error is now resolved.

**Comment by boelle** [comment]
closing as it is solved
