### ISSUE TITLE
Autoleveling: G0 Z0 going to not zero

### ISSUE THREAD

**Issue by orangeudav** [ErikZalm/Marlin#1290]
```
G90
G28 X0
G28 Y0
G29
[INFO] RECV: Bed x: 87.00 y: 2.00 z: 6.39
[INFO] RECV: Bed x: 17.00 y: 148.00 z: 6.66
[INFO] RECV: Bed x: 158.00 y: 148.00 z: 7.00
G0 Z0 
```
... and i got my head **under** heatbed level. I dont understand how it working and how it should working.
And yes, i calibrated Z_PROBE_OFFSET_FROM_EXTRUDER before.

**Comment by alexborro** [comment]
Try a G28 Z0 just before G29.
Em 02/01/2015 13:52, "orangeudav" <notifications@github.com> escreveu:

**Comment by orangeudav** [comment]
Your right, thank you!
