### ISSUE TITLE
createTemperatureLookupMarlin.py domain error

### ISSUE THREAD

**Issue by gaby64** [ErikZalm/Marlin#1305]
sometimes c3 is negative

adding

if c3 < 0:
    c3 = c3 * -1

seems to work, i get a working table

**Comment by stv0g** [comment]
Thanks, now I'm able to reproduce the error.

But I'm still investigating whether your fix is applicable.

Read this for an detailed explanation: http://www.thinksrs.com/downloads/PDFs/ApplicationNotes/LDC%20Note%204%20NTC%20Calculator.pdf

**Comment by gaby64** [comment]
thermistor reported temperature seems to agree with thermocouple measured temperature using the resulting table

**Comment by stv0g** [comment]
Okay, but the calculation doesn't matches with the Steinhart-Hart equation.
The correct solution is somehow complex:
http://m.wolframalpha.com/input/?i=-1%2Ft+%2B+a+%2B+b*log%28x%29+%2B+c*log%28x%29%5E3+%3D+0&x=0&y=0

**Comment by gaby64** [comment]
but are Steinhart-Hart coefficients allowed to be negative?

**Comment by boelle** [comment]
should be fixed... if not open new issue
