### ISSUE TITLE
Development: Add RAMPS heated chamber

### ISSUE THREAD

**Issue by vdirienzo** [ErikZalm/Marlin#1316]
i was thinking it should be easy to implement heated chamber with a ramps. marlin supports 3 extruders. ramps cant handle 3 extruders. but we can use the software already programed. to make 1 pin to read the temperature and other pin with relay can control any device to heat the chamber.

**Comment by boelle** [comment]
this has been asked before... will find it to make sure and close this one if i was right

**Comment by boelle** [comment]
https://github.com/ErikZalm/Marlin/issues/973

same request, his english is just not as good
