### ISSUE TITLE
Set GitHub default branch to 'Stable'

### ISSUE THREAD

**Issue by stv0g** [ErikZalm/Marlin#1317]
I'm still landing on the outdated 'Marlin_v1' branch when visiting https://github.com/ErikZalm/Marlin .

**Comment by nophead** [comment]
Also searches of the repository all seem to fail, presumably because the default branch is empty. I don't know how you change the branch it searches in.

**Comment by stv0g** [comment]
The default branch can be changed in the repository settings.

**Comment by boelle** [comment]
i have asked @ErikZalm for this over his private email

will do once more

**Comment by boelle** [comment]
done... he is the only one able to do it, collabs do not have enough rights for it

collabs dont have the settings... only @ErikZalm have those

**Comment by stv0g** [comment]
thanks :+1:

**Comment by boelle** [comment]
what i did was delete all files in V1 and change the readme so people at
least are shown the right way

@Erikzalm are very busy and it took me ages to get added as collab....

So well yes i did as best i good with the rights i have [?]

2015-01-06 11:43 GMT+01:00 Steffen Vogel <notifications@github.com>:
